### ISSUE TITLE
[BE] Boot de monitoramento

### ISSUE THREAD

**Issue by Raffiuds** [codenation-dev/squad-5-aceleradev-fs-online-1#8]
Criar um boot que monitora de forma contínua e automatizada caso um de seus clientes vire um funcionário público do estado de SP (http://www.transparencia.sp.gov.br/busca-agentes.html) ou seja um bom cliente com um salário maior que 20 mil reais.

**Comment by rmsphd** [comment]
criei um Cloud Scheduler que roda essa rotina todo dia as 06:00 da manha,
